### ISSUE TITLE
W19: Deleting augroup that is still in use

### ISSUE THREAD

**Issue by dbmrq** [henrik/vim-indexed-search#13]
Using the latest versions of Vim I get this error (W19) instead of the search index.

`:h W19` says not to use `augroup!` "if there is still an autocommand using this group", so I suppose that's what's happening here. I looked into your `s:destroy_augroup()` function and changed the line that says

```vim
execute "augroup! ". a:group
```

to 

```vim
execute "silent augroup! ". a:group
```

And it makes the plugin usable again, but I think this should be fixed properly, instead of just hiding the error message.

---

Edit: It seems that changing the `CursorHold` autocmd to this fixes this problem without changing anything in the functionality:

```vim
autocmd CursorHold *
    \ let &ut = s:save_ut            |
    \ call s:echo_index(s:force)     |
    \ autocmd! IndexedSearchAutoCmds |
    \ augroup! IndexedSearchAutoCmds
```

It seems like the `autocmd!` line at the `s:destroy_augroup()` function isn't doing its job for some reason.
I can make a PR if you want me to, I just didn't already because I'm not 100% sure this is the way to go.

**Comment by henrik** [comment]
Thanks for the thorough report!

@otommod, any thoughts on this?

**Comment by otommod** [comment]
Sorry about that.  Debian Sid doesn't yet have the latest vim.  So I built it and indeed I get W19.
However, in my "old" vim (7.4.1829), your code results in
```
Error detected while processing CursorHold Auto commands for "*":
E216: No such event: | augroup! IndexedSearchAutoCmds
```
Indeed, `:h :bar` mentions that `:autocmd` does not play well with it.

Still, there is hope!  We could omit the `augroup! ...` call.  I don't really think there is a reason to be destroying and remaking the augroup.  That seems to work fine for me in both the "old" and the latest vim.

Feel free to open such a PR then.

**Comment by dbmrq** [comment]
There you go, thanks. :)
