### ISSUE TITLE
Add case sensitive support

### ISSUE THREAD

**Issue by zhea55** [henrik/vim-indexed-search#15]
Can you add another mapping for search case sensitive when press * or #

**Comment by henrik** [comment]
Hi @zhea55. I think the plugin is meant to follow the behaviour of your Vim. (I didn't write it; I only put it on GitHub.)

Are you saying that your Vim searches case-sensitive without this plugin, but becomes case-insensitive without it?

**Comment by zhea55** [comment]
I set ignoreCase in my vimrc, and smartcase

but i want refactor some variable with * search variable, i want it be case sensitive.

i'm lazy, so i don't want type     set noic

I just want * # search can be case sensitive

and / ? search respect the vimrc setting.

**Comment by henrik** [comment]
Aha, alright. Not sure that's within the scope of this plugin. Maybe if you find or write another plugin that adds this behaviour to `*` and `#`, and you load the plugins in the right order, this one should just work.

Any thoughts, @otommod?

**Comment by otommod** [comment]
Yeah, I don't thing this has a place here... There're already some unrelated things (`dont_move`, `unfold` and `center`), but that seems like too much of a niche.
