### ISSUE TITLE
Did some testing, turns out we're slooow

### ISSUE THREAD

**Issue by otommod** [henrik/vim-indexed-search#20]
Recently, I found some other plugins that do the something as we are: providing an index into your searches.  I thought I'd take the time to check how they do things compared to us.  In particular, there is [vim-searchindex](https://github.com/google/vim-searchindex) that uses a complex caching algorithm and I thought "is this all necessary, I've never felt vim-indexed-search to be slow".  Turns out, I was just not searching (get it?? :D) enough.

## The competiton
So, without farther ado, let's see what we're up against.  I will be comparing two things: correctness, whether or not the results are correct in every case, and speed.

*   [henrik/vim-indexed-search](https://github.com/henrik/vim-indexed-search); that's us.

    - [ ] Correctness.  Our algorithm is actually not always correct.  In particular, star commands (`*`, `#`, `g*`, ...) do not respect the `smartcase` options while the `search()` vim function that we use does.  Try it out, run `set ignorecase smartcase`, write `foo Foo` in a buffer and "star" the second `Foo`.  While both of them are matches for vim we only report the one.

    - [ ] Speed.  We're actually slow, hence the name of the issue.  This was quite a surprise, given how simple the algorithm is, but as can be seen bellow, we're the slowest of the bunch.

*   [google/vim-searchindex](https://github.com/google/vim-searchindex)

    - [x] Correctness.  They provide a custom mapping for `*`, `#`, `g*` and `g#` and even an option to make these commands respect case.
    - [x] Speed.  They're really fast.  Like, for real.

*   [romainl/vim-cool](https://github.com/romainl/vim-cool); added a search index capability recently using a very unique approach.

    - [x] Correctness.  They manage to stay correct without any custom mappings by utilizing the same mechanism that the user is; the 'n' and 'N' commands.  This does mean that there are a number of edge cases to take into account but nothing unsolvable.
    - [ ] Speed.  The base algorithm as implemented in the plugin is very slow.  However, there are ways to get better performance.

## Benchmarks
Now, let's get a-measuring.  I created a 15kB file of random base64ed data, searched for `.` and used the profile functionality of vim to measure performance.  I run each algorithm 10 times at the very top of the file, 10 times in the middle and 10 times near the end.  Each time the cursor also moves a little so that the caching algorithms don't get away with doing literally nothing; they'll just do very little.

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   30  17.046901             <SNR>111_cool()
   30  13.101501             <SNR>111_current()
   30   8.098149             Cool_gallop()
   30   2.196443   2.192264  <SNR>111_vimgrep()
   30   0.337265   0.005592  Cool_cache_gallop()
   30   0.233058   0.227023  <SNR>111_substitute()
   30   0.025718   0.006094  <SNR>111_searchindex()
```

* `s:cool()` is the algorithm taken straight from the plugin
* `s:current()` is our current algorithm
* `Cool_gallop()` is an algorithm based on the "cool" idea (using just `n`, `N`) but it first searches using `10n`, the `n` command with a count of 10.  This is the same as doing `n` 10 times but since the loop is done internally it ends up being faster.
* `s:vimgrep()` uses, you guessed it, the vimgrep command.  While that is fast on its own, getting the results back is veery slooow (comparatively) since it passes a list with all the matches.  There's also the problem of correctness; vimgrep never uses `smartcase` so star searching will be correct, all the other ones won't be though.
* `Cool_cache_gallop()` tries to combine `Cool_gallop()` with the caching of vim-searchindex but it's still quite buggy.
* `s:substitute()` just uses substitute with the n flag that reports the number of matches.  It is very simple and fast but not at all correct; substitute works only linewise.
* `s:searchindex()` is the algorithm straight from the plugin.  At its core it uses substitute to count the matches in the lines above and then uses `search()` in the current line.  That on its own is fairly fast, however the secret sauce is its caching.  Using that, they only ever have to count the matches in the lines since the previous counting.

## Conclusions
Where do we go from here?

**Comment by polyzen** [comment]
Another contender: https://github.com/osyo-manga/vim-anzu (which can be used by https://github.com/haya14busa/is.vim).

**Comment by otommod** [comment]
@polyzen Ah, yes indeed.  They [seem to be using](https://github.com/osyo-manga/vim-anzu/blob/45b60d37cb9de90f6c89f7ddeacb7ae430ebcae2/autoload/anzu.vim#L165-L208) our algorithm though with some caching as well.

**Comment by henrik** [comment]
Wow, that’s some thorough research, Otto :)

Could it make sense for us to simply update the README and encourage using another of those faster and less buggy libraries, or do you think this specific plugin has some benefits that others lack?

**Comment by otommod** [comment]
Right, so I pushed a branch that introduces a new algorithm.  It's basically `Cool_gallop` mentioned above.  I opted for that approach because it just works(TM), without need for special mappings.  This gives the maximum flexibility for the user.

I also updated the README to mention all the plugins in this issue.  While we could just deprecate our plugin in favor of the others, the fact of the matter is that I like this plugin.  After all, it does more than just show the index.

**Comment by matt1003** [comment]
I am using the new branch, and it is noticeably a lot faster!

**Comment by otommod** [comment]
Have you noticed any bugs?  I'm thinking of merging the branch soon.

**Comment by otommod** [comment]
I guess (hope) the lack of answers means a lack of bugs, so I'm merging this.

**Comment by rburny** [comment]
@otommod - tangential to this bug, what are the features that `vim-searchindex` is missing? Although it has a philosophy of minimizing the number of options, functionalities like `g:indexed_search_dont_move` can be simulated through user-defined mappings (which, admittedly, could be better documented).

We could try migrating the functionality and merging the plugins, so that the users can have the best of both worlds.

**Comment by matt1003** [comment]
@otommod - I have not noticed any bugs.

**Comment by matt1003** [comment]
Does the performance improvements justify increasing ```g:indexed_search_max_lines```?

**Comment by otommod** [comment]
@matt1003 Probably.  I haven't done any measurements though.  What I'd really like is  a time constraint (say, 100ms).

@rburny I'd like to think that what `vim-indexed-search` provides is a "full" package.  I'm not against merging, though I'm also kind of fond of this new algorithm.

**Comment by rburny** [comment]
@otommod I'm trying to understand what does "full package" mean. Reading the documentation, I see that `vim-indexed-search` has additional movement-related options: `g:indexed_search_dont_move, g:indexed_search_center`. Anything else that `vim-searchindex` is missing?

**Comment by otommod** [comment]
@rburny Nope.
