### ISSUE TITLE
breaks / selection

### ISSUE THREAD

**Issue by mcepl** [henrik/vim-indexed-search#21]
When I run command like ``vc/ `` (select to the next space), or some other command which takes search result as an object, that selections just blinks for a second and collapses again, so in the end nothing is selected. I guess some unruly times is at fault, but when I uninstalled this plugin (because this functionality is very important for me), everything works fine again.

Using neovim from HEAD on RHEL-7 (neovim/neovim@8d5a46e77 ATM).

**Comment by otommod** [comment]
Is this a plugin mapping?  In "standard", `c` (see [`v_c`](http://vimdoc.sourceforge.net/htmldoc/change.html#v_c)) in visual mode just "changes" the selections (deletes it and enters insert mode).

In any case, this is probably related to afffc44a0715bde43efbf79382db363072ef4787.

**Comment by mcepl** [comment]
Perhaps, certainly it is not any of my own mappings.

**Comment by otommod** [comment]
Could you perhaps share your `.nvimrc` (or how they call it)?

**Comment by mcepl** [comment]
I keep [~/.vim/vimrc](https://github.com/henrik/vim-indexed-search/files/1866428/vimrc.txt) compatible with both vim8 and Neovim.

**Comment by otommod** [comment]
What does `:map c/` say?

**Comment by mcepl** [comment]
``No mapping found.``

**Comment by otommod** [comment]
What about `:map vc/` ?

**Comment by mcepl** [comment]
same

**Comment by otommod** [comment]
So, I'm guessing that you were just doing `c/`, i.e. change till the next result, or similarly `v/`.  And that indeed is broken.

**Comment by otommod** [comment]
Pushed f065be8a15c94943aec75ed5978705d8c6cc8b39, try it out.

**Comment by mcepl** [comment]
Wow! Awesome! Thank you.
