### ISSUE TITLE
Key maps doesn't work in latest commits in Neovim

### ISSUE THREAD

**Issue by unclechu** [henrik/vim-indexed-search#22]
My config: https://github.com/unclechu/neovimrc
You could look at this commit that freezes commit before update which is working:
https://github.com/unclechu/neovimrc/commit/52b5029b32176a04786dd9c798a91df285a6fbec#diff-23d016fb30028357a122b2cb3d106ee2R23
This one: henrik/vim-indexed-search@5f36c32 

When I press any key mapped to `<Plug>(indexed-search-...` nothing just happens.
You could find my own these maps here: https://github.com/unclechu/neovimrc/blob/master/maps.vim
It doesn't works in even latest Neovim (`NVIM v0.2.3-934-g98e7112` dated by 31 March 2018). I don't have any info if it's working in Vim or not.

I realized it isn't working first time with this commit: henrik/vim-indexed-search@cfc43d5

**Comment by otommod** [comment]
Also, you also have to define `<plug>(indexed-search-index)` since that is also hidden behind the option

```vim
map  <plug>(indexed-search-index)  :ShowSearchIndex<cr>
xmap <plug>(indexed-search-index)  :<u-u>ShowSearchIndex<cr>gv
```

**Comment by mcepl** [comment]
Hmm, again, when in neovim, when I run ``c/~`` (tilda is used to display space character), I get ``zv<Plug>(indexed-search-index)`` inserted into the text. Not good.

**Comment by unclechu** [comment]
@otommod I have my own maps for `*`/`#`, in my case it's mapped on `@`/`!` so I prefer to set `g:indexed_search_mappings` to `0`. But I can't reach some functions from here https://github.com/henrik/vim-indexed-search/blob/7c20bef9e2bcb8d7ad09963abfced378dbd6f2e9/plugin/indexed-search.vim#L129-L151 to make my own maps, `s:star`, `s:n`, `s:after` and `s:restview` they're private, so I can't reach it, maybe it would be good to make them public to be able to make own maps or to have some global variables for custom keys: https://github.com/henrik/vim-indexed-search/blob/7c20bef9e2bcb8d7ad09963abfced378dbd6f2e9/plugin/indexed-search.vim#L145-L150?

**Comment by unclechu** [comment]
I mean, I done what I actually wanted by calling `:ShowSearchIndex<CR>` in my maps, but this behavior is little different, am I right?

**Comment by otommod** [comment]
@unclechu Well, yeah.  But unless you need any of the other features that the plugin's mappings provide (look up `g:indexed_search_dont_move`, `g:indexed_search_center` and `g:indexed_search_n_always_searches_forward`) it doesn't matter.
