### ISSUE TITLE
Breaks visual star search

### ISSUE THREAD

**Issue by jondkinney** [henrik/vim-indexed-search#23]
This could be related to https://github.com/henrik/vim-indexed-search/issues/21 but I'm also using another plugin, [nelstrom/vim-visual-star-search](https://github.com/nelstrom/vim-visual-star-search) and it seems like vim-indexed-search is causing an issue. 

If I visually select some text, say something inside quotes like `'henrik/vim-indexed-search'`, without this plugin the whole bit inside the quotes, that whole string stays highlighted and vim shows me other instances of that same full string. But with this plugin installed, the highlighted selection pops over to the last word in the string. so in the case above, it'd only highlight the `search` bit of the `'henrik/vim-indexed-search'` string. Any thoughts? Thanks!

**Comment by henrik** [comment]
Hi,

Thanks so much for the report! @ottommod, anything you’re interested in looking into?

**Comment by otommod** [comment]
Which plugin are you loading first?  I'm guessing `vim-indexed-search`.  Try doing it the other way around.

I'm guessing you've set `g:indexed_search_dont_move` which did have a bug (see cb610beb808076109ba98b1f7774b5fb2ea1fd8e)

**Comment by jondkinney** [comment]
@otommod thanks for the quick reply! I was actually loading `vim-visual-star-search` first, but putting `vim-indexed-search` ahead of it in the list mostly gets me there! It fixes the issue of not retaining the visual selection when pressing `*`. However, the `g:indexed_search_dont_move` setting, which yes, I have set at 1, doesn't seem to be sticking now. I did update the plugin to the latest version. Any thoughts there? Thanks again!

**Comment by otommod** [comment]
That's because in the bugged case you're using `vim-visual-star-search` mapping which obviously doesn't respsect any of our options; you'll also notice that the search index doesn't show up either.  I don't thing there's anything that can be done really.  There can only one mapping for a single key and mode.

**Comment by henrik** [comment]
Closing old issue to keep things tidy.
