### ISSUE TITLE
Breaks backward search with S-# + n

### ISSUE THREAD

**Issue by InterAl** [henrik/vim-indexed-search#24]
Please remove the feature introduced by this commit:

https://github.com/henrik/vim-indexed-search/commit/96703afef647aef4ac2a303df3848e8f0dffc327

I don't understand how it is relevant to the purpose of this plugin - seems like it should be in a plugin of its own. Plus, it breaks the default vim behavior and is poorly documented. If anything, I think the default value should be "0" and let those who're interested in this quirk switch it to "1".

**Comment by henrik** [comment]
Hi @InterAl!

That sounds like a reasonable change to make. @jlesquembre and @otommod, any thoughts? If I don't hear anything, I think I'll change the default to "0" in a day or two.

**Comment by jlesquembre** [comment]
To me, makes more sense that `n` and `N` always search in the same direction, but if you don't agree with it, totally fine with me to change the default to `0`

I don't understand what my PR broke, @InterAl could you provide an example?

**Comment by InterAl** [comment]
It broke the default vim behavior. Yes, I think it's better to change the default to 0, but even then - I don't see why this plugin needs this feature at all. I believe it's out of scope and should be featured in a plugin of its own.

**Comment by otommod** [comment]
I'm fine with make 0 the default.  The problem with moving this in it's own plugin is that it'd need to map `n/N` and we're already doing that so one plugin would completely overwrite the other one.  That's the reason for all the other options of this plugin.

**Comment by leodotcloud** [comment]
@jlesquembre 
`/wordtosearch` -> does a forward search. `n` for next, `N` for previous
`?wordtosearch` -> does a backward search. `n` for next, `N` for previous

If I want to search from end of file I would go to end of file and use `?` and then press `n`. This is the default vim behavior. I couldn't use this functionality for quite some time. Today I just got so frustrated of this missing behavior, started drilling down and found this issue.

Request you to not change default vim behavior.

**Comment by henrik** [comment]
@leodotcloud Yeah, based on this feedback I'll change the default to 0 :thumbsup:

**Comment by henrik** [comment]
Should be fixed by https://github.com/henrik/vim-indexed-search/commit/5af020bba084b699d0453f242d7d76711d64b1e3.
