### ISSUE TITLE
Respect existing mappings

### ISSUE THREAD

**Issue by FreGalle** [henrik/vim-indexed-search#8]
Currently I have `nmap n nzz` and `nmap N Nzz` in my vimrc to center the screen on the matches when cycling through them. I tried changing the `nnoremap`s in vim-indexed-search with `nmap`s thinking that would allow me to have both, but for some reason that didn't work.

Any idea how what else I would need to change or could you add an option to allow remaps/centering?

**Comment by henrik** [comment]
Hey,

I mostly just put this on GitHub, so I don't really maintain it.

But going by the code, if you do `let g:indexed_search_mappings = 0` before the plugin is loaded, it won't set up its own mappings. Or, you could overwrite its mappings with your own after it loads.

See here for the built-in mappings: https://github.com/henrik/vim-indexed-search/blob/master/plugin/IndexedSearch.vim#L92

**Comment by henrik** [comment]
I'll close this since I don't plan on adding anything, but I'll accept a pull request if someone else wants to do it.

**Comment by otommod** [comment]
@FreGalle Yeah, I though that something like that would work too (hence #5 and 206137de44266e036598a17b54371d12d8ee0c84). Unfortunately, it doesn't work. If you know any way, do say so. The current solution (having different mappings for specific situations) certainly isn't scalable.

**Comment by FreGalle** [comment]
I looked into it some more and it looks like vim only keeps track of 1 mapping per *key-mapping*.

```VimL
nnoremap j dd
nmap j jj
```
will not result in `j` deleting two lines. What happens is that the first mapping is removed as soon as the second one is defined and the second one executes recursively in terms of itself, so `jjjjjjjjjjjjj...` is what will happen.

The same is true in this plugin. Because its mappings load after the user's vim configuration, the user's mappings are thrown out and new mappings are set up.

A solution would be for the plugin to save the current mapping to a new variable and set up its mappings in terms of that new variable. I am however not familiar with VimScript, is this something you think can be done, @otommod ?

**Comment by otommod** [comment]
@FreGalle Well, it can be done I guess, but there are a lot of special cases. Like, for example, if the original mapping (the one in your `.vimrc`) was an expression mapping (`map <expr>`), then we'd have to transform it to a regular one in some way. Vim doesn't do that for us. Otherwise, the mapping that the plugin will create won't execute yours properly. Also, if you happen to create some buffer-local mapping, this will always overwrite this plugins mappings.

So, I don't think that's the way to go. I could use `map <unique>`, so that would error out when the plugin tried to overwrite a mapping you have in your `.vimrc` but that could lead to some hard to-do debugging on the users' part.

I could create some `<Plug>` mappings though, that would make creating your own much easier.

**Comment by FreGalle** [comment]
Yeah, it doesn't look like there is a silver bullet here.

How would the `<Plug>` mappings solve the problem of the user's mappings being overwritten by the plugin's?

**Comment by otommod** [comment]
It would make it easier to create your own.
For example, if you wanted to add `echo "foo"<CR>` before `n`, you would just have to do
```vim
autocmd VimEnter * nmap n :echo "foo"<CR><Plug>(indexed-search-n)
```
instead of
```vim
autocmd VimEnter * nnoremap n :echo "foo"<CR>n:ShowSearchIndex<CR>
```

Whether that is much easier is debatable. In both cases, the `autocmd` is unavoidable, otherwise the plugin will overwrite them...

**Comment by FreGalle** [comment]
Great, that would make things easier to manage indeed.

**Comment by henrik** [comment]
> In both cases, the autocmd is unavoidable, otherwise the plugin will overwrite them...

Is it not avoidable if you set `let g:indexed_search_mappings = 0` before the plugin loads?

**Comment by otommod** [comment]
Well, yeah, in that case you don't need the `autocmd`, but then you'd have to do all the mappings yourself, `/`, `?`, `n`, `N`.

**Comment by otommod** [comment]
@FreGalle Sorry for the delay, I pushed a commit to the plug-mappings branch, can you test it out?

**Comment by FreGalle** [comment]
I tried remapping n and N with the new <Plug> commands and they both worked flawlessly.

**Comment by otommod** [comment]
I merged this branch now.

**Comment by gyermolenko** [comment]
for those who come after me: 
If you want to center your cursorline after hitting next object - use this:
autocmd VimEnter * nmap n <Plug>(indexed-search-n)zz
autocmd VimEnter * nmap N <Plug>(indexed-search-N)zz

**Comment by otommod** [comment]
@gyermolenko, @FreGalle 
I pushed a branch center-cursor that introduces the `g:indexed_search_center` option. It is off by default, but otherwise do what you want.

**Comment by gyermolenko** [comment]
so far - no updates in plugin...

**Comment by otommod** [comment]
@gyermolenko Check the `center-cursor` branch...

**Comment by lfilho** [comment]
@otommod but why is that branch not merged into master?

**Comment by otommod** [comment]
@lfilho I have no idea... I believe I was planning to merge it but then forgot about.
Anyway, merged.  Be sure to report any bugs if you find them (hopefully and probably not).

**Comment by lfilho** [comment]
Great! Will give it a go soon!! Thank you!

**Comment by lfilho** [comment]
I put `g:indexed_search_center=0` in my .vimrc but while opening vim i get this error:
```
Pattern not found: indexed_search_center=0
```
Did i miss anything? Also it would be a good idea to update the README teaching people about that option and how to properly config it

Thanks again :)

**Comment by otommod** [comment]
Did you do `let g:indexed_search_center = 0` ? Also, 0 is the default so you don't need to do that.

**Comment by lfilho** [comment]
Ah! I forgot the `let`! Worked liked a charm! Thanks!
